[package]
name = "token-tree"
version = "0.20220719.0-dev"
license = "MIT OR Apache-2.0"
edition = "2021"
description = "token-tree"

[dependencies]
once_cell = "1.13.0"
proc-macro2 = { version = "1.0.40", features = ["span-locations"] }
serde = { version = "1.0.139", features = ["derive", "rc"] }
